#!/usr/bin/env bash
# Install nginx on your web-01 server


sudo apt-get update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

# testing nginx configuration

sudo nginx -t
sudo service nginx reload
