#!/usr/bin/env bash
#a Bash script that ping an IP adress passed as an ARG
#accept strind as an arguments

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
