#!/usr/bin/env bash
# Displays on the console "Best School" 10 times 
# use a while loop.
#On the 9th itearation, 
# write greting "Hi"
#then "Best School".

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( i++ ))
done
