#!/usr/bin/env bash
# Displays time 12 hrs and 59 minutes.
# Displays hrs from 0 to 12
# Displays min from 1 to 59

hrs=0

while [ $hrs -le 12 ]
do
  echo "Hour: $hour"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hrs++ ))
done

