#!/usr/bin/env bash
# Displays the contents of the current directory in list.
# Only displays the part of the name after the first dash. 

list=$(ls)
for items in $list; do
  echo "$items" | cut -d '-' -f2
done
